spring:
  application:
    name: MetaDBA

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metadba?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: bmjwanm801
server:
  port: 9999
mybatis:
  configuration:
    map-underscore-to-camel-case: true
